---
title: "Shiny App Log"
author: "John Froeschke & Claire Roberts"
date: "March 3, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Status and Log of Shiny apps

### Coral HAPC
* Author(s)
* URL (if deployed)
* Git Repository
* Purpose
* Last commit
* First commit
* Current version
    
* To-do list
    + Convert all pop-ups to mapview
    + ~~Add dynamic base map of nautical chart~~
    + ~~Update addMouseCoordinates2~~
    + ~~Remove mapview dependency~~
    
### EFH
* Author(s)
* URL (if deployed)
* Git Repository
* Purpose
* Last commit
* First commit
* Current version
* To-do list
    + Add second y axis to age-length for inches display
    + ~~Bookmarking for specific pages for referencing in documents~~ CER
    + Size at maturity markers on age/growth charts
    + https://cran.r-project.org/web/packages/secret/index.html (New 07/06/2017)

### Lobster Applications
* Author(s) : Claire Roberts, John Froeschke
* URL (if deployed) http://portal.gulfcouncil.org/SpinyLobsterManagement.html
* To-do list
    + Coordinates of each polygon in pop-up, considere html table from mapview
    + add download link for shapfile or tabular data.  Could fortify the data into a readable table using the fortify function in ggplot2

